################ Device ################
device: "gpu"


################ Dataloader ################
pickles_path_eval: [
  "./datasets/cifar10/test_batch",
]
preprocessing_method: "normalized"    # "normalied" or "standardized" or "none"


################ Torch Dataloader ################
batch_size: 20
num_workers: 0


################ Model ################
vectorize_input: false
model: 
  input_channel: 3
  layers_config: [
    "conv3x3_64",
    "batchnorm",
    "relu",
    "conv3x3_128",
    "batchnorm",
    "relu",
    "maxpool",
    "inception_64_96_96",
    "inception_64_96_96",
    "maxpool",
    "conv3x3_512",
    "batchnorm",
    "relu",
    "maxpool",
    "inception_64_96_96",
    "gap",
    "linear_10"
  ]
pretrained_model: "./trained_net.pth" 


################ Loss Function ################
loss_type: "softmax_cross_entropy"        # "mse" or "softmax_cross_entropy"


################ Optimizer ################
optimizer_type: "sgd"                     # "sgd" or "adam"
lr: 0.001
momentum: 0.99


################ Training ################
num_epochs: 20


################ Reporting ################
eval_report_path: "./test_report.csv"

